name: Build Windows EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kivy==2.3.1 pyinstaller==6.22.2

      - name: Build EXE
        run: python -m PyInstaller --clean --noconfirm Hisaab-Mate.spec

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: Hisaab-Mate-Windows
          path: dist/Hisaab-Mate.exe